version: "3.7"

services:
  redis:
    image: redis:7.0.5-alpine3.16
    container_name: redis_${PROJECT_NAME}
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf

  web:
    depends_on:
      - redis
